<?php

namespace app\components\widget\vue;

use yii\base\Widget;

class VueWidget extends Widget
{
    public string $component;
    public array $params;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
    }

}